language: node_js
node_js:
  - "8.10"
jobs:
  include:
    - stage: "Deploy Server"
      before_install:
        # - ./checkdiff.sh server/*
        - cd server
      install: npm install
      script:
      - STAGE="$( echo $TRAVIS_BRANCH | tr '/' '-' )"
      - npm run deploy -- --stage $STAGE
    - stage: "Deploy Client to S3"
      before_install:
        # - ./checkdiff.sh client/*
        - cd client
      install: npm install
      before_script:
        - echo VUE_APP_API_GATEWAY_STAGE=$TRAVIS_BRANCH > .env
        - cat .env
      script:
        - npm run build
        - mkdir build
        - cd dist
        - zip -r ../build/"$TRAVIS_BRANCH"_"$(date +%Y-%m-%d)"_"$TRAVIS_BUILD_NUMBER".zip *
        - cd ..
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: twitch-channel-feed-client-build
        region: ap-northeast-2
        skip_cleanup: true
        local_dir: build
        upload-dir: $TRAVIS_BRANCH
        on:
          all_branches: true

