service: server

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
  region: ap-northeast-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
# you can define service wide environment variables here
  environment:
    TWITCH_EXTENSION_SECRET_KEY: "${self:custom.secrets.TWITCH_EXTENSION_SECRET_KEY}"

# you can add packaging information here
package:
 exclude:
   - secrets.yml

functions:
  hello:
    handler: feed.post
    events:
      - http:
          path: feed
          method: post
    handler: emote.emote
    events:
      - http:
          path: emote
          method: post

custom:
  secrets: ${file(secrets.yml)}